/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DisposalsRouteImport } from './routes/disposals'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsAssetIdRouteImport } from './routes/assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DisposalsRoute = DisposalsRouteImport.update({
  id: '/disposals',
  path: '/disposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/cashflow': typeof CashflowRoute
  '/decisions': typeof DecisionsRoute
  '/disposals': typeof DisposalsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/strategy': typeof StrategyRoute
  '/valuation': typeof ValuationRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/cashflow': typeof CashflowRoute
  '/decisions': typeof DecisionsRoute
  '/disposals': typeof DisposalsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/strategy': typeof StrategyRoute
  '/valuation': typeof ValuationRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/cashflow': typeof CashflowRoute
  '/decisions': typeof DecisionsRoute
  '/disposals': typeof DisposalsRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/strategy': typeof StrategyRoute
  '/valuation': typeof ValuationRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisitions'
    | '/assets'
    | '/cashflow'
    | '/decisions'
    | '/disposals'
    | '/pipeline'
    | '/portfolio'
    | '/risk'
    | '/strategy'
    | '/valuation'
    | '/assets/$assetId'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisitions'
    | '/cashflow'
    | '/decisions'
    | '/disposals'
    | '/pipeline'
    | '/portfolio'
    | '/risk'
    | '/strategy'
    | '/valuation'
    | '/assets/$assetId'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/acquisitions'
    | '/assets'
    | '/cashflow'
    | '/decisions'
    | '/disposals'
    | '/pipeline'
    | '/portfolio'
    | '/risk'
    | '/strategy'
    | '/valuation'
    | '/assets/$assetId'
    | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionsRoute: typeof AcquisitionsRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  CashflowRoute: typeof CashflowRoute
  DecisionsRoute: typeof DecisionsRoute
  DisposalsRoute: typeof DisposalsRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRoute
  RiskRoute: typeof RiskRoute
  StrategyRoute: typeof StrategyRoute
  ValuationRoute: typeof ValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disposals': {
      id: '/disposals'
      path: '/disposals'
      fullPath: '/disposals'
      preLoaderRoute: typeof DisposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionsRoute: AcquisitionsRoute,
  AssetsRoute: AssetsRouteWithChildren,
  CashflowRoute: CashflowRoute,
  DecisionsRoute: DecisionsRoute,
  DisposalsRoute: DisposalsRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRoute,
  RiskRoute: RiskRoute,
  StrategyRoute: StrategyRoute,
  ValuationRoute: ValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
